# hiện tên thẳng trên giao diện github
name: CI Pipeline 
# Đây là một workflow CI đơn giản với hai job: test và build. Job test sẽ chạy trước và tạo ra các artifact giả để minh họa việc upload kết quả test và coverage. Job build sẽ chạy sau khi job test hoàn thành thành công. Bạn có thể thay thế phần run trong mỗi step bằng các lệnh thực tế để chạy test và build dự án của bạn.
on:
  push:
    branches:
      - '**'
      - '!main' # vì ko cho push lên main 
  pull_request:
    branches:
      - 'main'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: test # Tên này sẽ hiển thị trong ô tìm kiếm Status checks của bạn
    runs-on: ubuntu-latest
    
    steps:
      - name: In kết quả Test
        run: echo "Test thành công!"
        
      - name: Tạo file report giả để upload
        run: |
          mkdir coverage test-results
          echo "Day la ket qua coverage gia lap" > coverage/coverage.txt
          echo "Day la ket qua test gia lap" > test-results/result.txt

#tạo artifact để upload / tạo độ phủ cho testcase  
      - name: Upload Test Coverage
        uses: actions/upload-artifact@65c86da06ee04569841a3397701959d1a7774074 # v4
        with:
          name: coverage-report
          path: coverage/

      - name: Upload Test Results
        uses: actions/upload-artifact@65c86da06ee04569841a3397701959d1a7774074 # v4
        with:
          name: test-results
          path: test-results/

  build:
    name: build # Tên này sẽ hiển thị trong ô tìm kiếm Status checks của bạn
    needs: test # Bắt buộc Test chạy xong mới tới Build
    runs-on: ubuntu-latest
    
    steps:
      - name: In kết quả Build
        run: echo "Build thành công!"