name: Media Service - Feature CI

on:
  push:
    branches:
      - 'test_feature_media*'
      - 'features/media/*'
    paths:
      - 'media/**'
      - '.github/workflows/actions/action.yaml'
      - 'pom.xml'
  workflow_dispatch:

jobs:
  test_and_scan:
    name: Security Scan & Unit Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Java/Maven Environment
        uses: ./.github/workflows/actions

      - name: Setup Snyk CLI
        uses: snyk/actions/setup@master

      - name: Snyk Security Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --severity-threshold=high --file=media/pom.xml

      - name: Run JUnit Tests & Generate Coverage
        run: mvn clean test -pl media -am
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

 
  build:
    name: Build Media Service
    needs: test_and_scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java/Maven Environment
        uses: ./.github/workflows/actions

      - name: Run Maven Build Command
        run: mvn clean install -pl media -am -DskipTests
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
